sudo: required
language: generic
services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
- docker-compose build
- docker tag transport-backend $AWS_ECR_IMAGE
- docker push $AWS_ECR_IMAGE
- aws ecs list-tasks --cluster $AWS_CLUSTER_NAME --region ap-southeast-1 | jq -r ".taskArns[]"
  | awk '{print "aws ecs stop-task --cluster $AWS_CLUSTER_NAME --region ap-southeast-1
  --task \""$0"\""}' | sh
- aws ecs run-task --cluster $AWS_CLUSTER_NAME --task-definition $AWS_TASK_DEF --count
  1 --region ap-southeast-1
env:
  global:
  - secure: VjlREVz4ASTKsfwGJV8bSRFWDSiIU1Y4zxZ2fX3ue/JlVYQgFamZwCSPK59GbheNYezoivPE7ZiWzPHORDikKoTvzl8nHIxjvShEV58EgaeYSxdL+qqq8kzYvMA8oGjZv4O0NaN8d0LYJKM8w+2FdZX4X/zMNOZ9qseD0ZesZ2C49c7a0NTd6k9YoQnX/MgCuMU1SNkionqTMgFinOIhNKwQwe3apm8Xmx1HLARE25aup3Zxm40ovQyP2FaddTD9iez+74hvzx+K0GOpvO86PuuOH3Zo9s4+wptsMdMAEpUjNxrGr+oHI8Z+q1AFolUr2ucsokurzmPynKyWb8A2i6yf//2Uivrzg/BGdJieDJj+eL91+IjkDA9cJEOvnh1UrpRBVq/filQtClHx5OXFr90EldPqjrhhP/aCTZ8cDheEHz5FAFEK40+zNjltV0QiOnNg9dNLc55BXQmtRtC642bU37WEgiOmFvVkDruOKx0E+CAFuAS+WBauaoM9PUvo0F8+LbYekQHJAvu0wnngJWQH8gQmMmYGpudM0MfJBOBCZpIKVlvW39a/gehGhh76WCexRxOmSd7GYEhRTleEj+kpxHafhuLGYRHjLJpwG54nU+TLxnpSvDqTV/V89DLVxkg96aG9GrOotpnmVSP9AD2a0zP3HcT9MGbEtcgWROQ=
  - secure: UB0flB9i/gs1l0VqAPIQxx3Jrjmbof6MkUxE9S5GpumAdYmpZhrxoQPj2CcIN6tBtfy5PeKPivzYQrLgIZUALawEYiSmp+rwIlSey+0RzUvMb3XiQ/m0K8nzLHJeBImgaFd1enVE0khPFnVblwCZe/fen5vOpA8XtjPFlVQpuETYTQT5dYfKdnUc0Wt5pdt8uF2ruG0iNpXr9nShIFLVDd3pZBmKs6jQVufxfDt2fFY7+qUApJDxcB/w8LJqEvG4FgbC/Y4NnzR9yym5VMtgEpM3+qp3DzuVfICXFIqVVu7QgYatKHW3CmXvxt0yXjwrMVHWxjVi5WUJKUMXV5xVH7PrsClXUfivN9EP+VkvQkdrnWwhz3Unn6+JZKU9y5uRh6x9dJ72xtJQY493VXFf5FMxuXdrkrzwhMlQaOItAjrlu/LOdSAH3aK8A8BvIsI5YQIpmTP1fPtucJ60bRVfp3PRlz6OG781lX/j+4mJ/HB8iRoYzlc60Rn5kPK3buPlc6aRfzHyFHE6JM6LPN+CmEov29QG1etUSAaPYdwUD1IWWEG4PAF3NrhHTh+3qLbGsVHYOnglHG4Bc5/zxyGBVtoGSLkfNINvlB1l86szDTw0GspMzL/eeVhTNLTNEeJnjYDohL3FkvWOqAruu8vOnsmjizxvXc7E/ueUyalei5Q=
